### ISSUE TITLE
token retrieve url throwing 401 error

### ISSUE THREAD

**Issue by guptaarun111** [eclipse/keti#36]
Below UAA Token retrieve URL is throwing 401 error, as we are not passing basic authentication credentials  ( app:appclientsecret) to uaa from keti. Looks like  config issue, Can someone help me on this.

http://localhost:8080/uaa/token_key  

Direct call to the URL from postman client  with correct password runs correctly and returns proper response.

Ket Log trace

Keti log trace......

20:28:05,579 ERROR FastTokenServices:300 - Unable to retrieve the token public key. 401 
20:28:05,625  WARN HttpChannel:510 - /v1/zone/demo
org.springframework.web.client.HttpClientErrorException: 401 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:63)
	at com.ge.predix.uaa.token.lib.FastTokenServicesResponseErrorHandler.handleError(FastTokenServicesResponseErrorHandler.java:34)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:559)
	at com.ge.predix.uaa.token.lib.FastTokenServices.getTokenKey(FastTokenServices.java:298)
	at com.ge.predix.uaa.token.lib.FastTokenServices.computeSignatureVerifier(FastTokenServices.java:132)
	at com.ge.predix.uaa.token.lib.FastTokenServices.lambda$initTokenKeysCache$0(FastTokenServices.java:124)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3159)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1984)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1982)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1965)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at com.ge.predix.uaa.token.lib.FastTokenServices.loadAuthentication(FastTokenServices.java:172)
	at com.ge.predix.uaa.token.lib.AbstractZoneAwareTokenService.authenticateNonZoneSpecificRequest(AbstractZoneAwareTokenService.java:123)
	at com.ge.predix.uaa.token.lib.AbstractZoneAwareTokenService.loadAuthentication(AbstractZoneAwareTokenService.java:95)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:83)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)

Regards,
Arun

**Comment by sanjeevchopra** [comment]
Credentials should not be needed for asymmetric keys - see https://docs.cloudfoundry.org/api/uaa/version/4.31.0/index.html#asymmetric

**Comment by guptaarun111** [comment]
> Credentials should not be needed for asymmetric keys - see https://docs.cloudfoundry.org/api/uaa/version/4.31.0/index.html#asymmetric . Please attach the uaa yml being used to this issue.

Please find attached uaa.yml file
[uaa.txt](https://github.com/eclipse/keti/files/3183008/uaa.txt)

**Comment by sanjeevchopra** [comment]
> > Credentials should not be needed for asymmetric keys - see https://docs.cloudfoundry.org/api/uaa/version/4.31.0/index.html#asymmetric . Please attach the uaa yml being used to this issue.
> 
> Please find attached uaa.yml file
> [uaa.txt](https://github.com/eclipse/keti/files/3183008/uaa.txt)

I'd like to help, though  I don't have any time to spend on this right now and I don't recall what you might be missing in the uaa config.   Please file a question with the uaa team.  You should not need a credentials to get verifying (asymmetric) key.
